steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - get_pricelist_json
  - --gen2
  - --region=us-central1
  - --source=./backend
  - --allow-unauthenticated
  - --trigger-http
  - --runtime=python310
  env:
  - 'PROD=True'
