steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - get_pricelist_json
  - --gen2
  - --region=us-central1
  - --set-env-vars=PROD=True,BUCKET_ID=cost2cost-storage
  - --source=./backend
  - --trigger-http
  - --runtime=python310
